services:
  db:
    image: mysql:8.4
    container_name: sparky-db
    restart: always
    environment:
      MYSQL_DATABASE: sparky
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: sparky-api
    restart: on-failure
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sparky?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

volumes:
  db_data: